CREATE TABLE USERS (
    USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(64) NOT NULL,
    USERNAME VARCHAR(8) NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    USER_TYPE VARCHAR(1) NOT NULL
);

CREATE TABLE STUDENTS (
    STUDENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(64) NOT NULL,
    LAST_NAME VARCHAR(64) NOT NULL,
    CLASS_NUM INT
);

CREATE TABLE PARENTS (
    PARENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CHILD_ID_1 BIGINT,
    CHILD_ID_2 BIGINT,
    CHILD_ID_3 BIGINT,
    CHILD_ID_4 BIGINT,
    CHILD_ID_5 BIGINT,
    FIRST_NAME_1 VARCHAR(64) NOT NULL,
    LAST_NAME_1 VARCHAR(64) NOT NULL,
    FIRST_NAME_2 VARCHAR(64) NOT NULL,
    LAST_NAME_2 VARCHAR(64) NOT NULL
);

CREATE TABLE TEACHERS (
     TEACHER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
     FIRST_NAME VARCHAR(64) NOT NULL,
     LAST_NAME VARCHAR(64) NOT NULL,
     CLASS_NUM INT(11)
);

CREATE TABLE CLASSES (
    CLASS_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CLASS_NUM INT(3),
    SECTION_NUM INT(3)
);

CREATE TABLE ASSIGNMENTS (
     ASSIGNMENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
     ASSIGNMENT_NAME VARCHAR(255) NOT NULL,
     POINTS_POSSIBLE INT NOT NULL,
     CLASS_NUM INT NOT NULL
);

CREATE TABLE GRADES (
    GRADE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ASSIGNMENT_ID BIGINT NOT NULL,
    STUDENT_ID BIGINT NOT NULL,
    POINTS_GIVEN INT NOT NULL,
    LETTER_GRADE VARCHAR(2) NOT NULL,
    FEEDBACK VARCHAR(255)
);

ALTER TABLE STUDENTS ADD FOREIGN KEY (STUDENT_ID) REFERENCES USERS(USER_ID);
ALTER TABLE PARENTS ADD FOREIGN KEY (CHILD_ID_1) REFERENCES STUDENTS(STUDENT_ID);
ALTER TABLE PARENTS ADD FOREIGN KEY (CHILD_ID_2) REFERENCES STUDENTS(STUDENT_ID);
ALTER TABLE PARENTS ADD FOREIGN KEY (CHILD_ID_3) REFERENCES STUDENTS(STUDENT_ID);
ALTER TABLE PARENTS ADD FOREIGN KEY (CHILD_ID_4) REFERENCES STUDENTS(STUDENT_ID);
ALTER TABLE PARENTS ADD FOREIGN KEY (CHILD_ID_5) REFERENCES STUDENTS(STUDENT_ID);
ALTER TABLE PARENTS ADD FOREIGN KEY (PARENT_ID) REFERENCES USERS(USER_ID);
ALTER TABLE TEACHERS ADD FOREIGN KEY (TEACHER_ID) REFERENCES USERS(USER_ID);
ALTER TABLE ASSIGNMENTS ADD FOREIGN KEY (CLASS_NUM) REFERENCES CLASSES(CLASS_NUM);
ALTER TABLE GRADES ADD FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID);
ALTER TABLE GRADES ADD FOREIGN KEY (ASSIGNMENT_ID) REFERENCES ASSIGNMENTS(ASSIGNMENT_ID);
ALTER TABLE GRADES ADD FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID);
